# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$browser = $HOME/.local/bin/brave_smart_open
$editor = code
$fileManager = thunar
$menu = rofi -show drun
$terminal = kitty

#################
### AUTOSTART ###
#################

exec-once = hyprpaper

####################
### SOURCE FILES ###
####################

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
