general {
  hide_cursor = true
}

animations {
  enabled = true
  bezier = linear, 1, 1, 0, 0
  animation = fadeIn, 1, 2, linear
  animation = fadeOut, 1, 2, linear
  animation = inputFieldDots, 1, 1, linear
}

background {
  path = ~/.config/blurry_wallpaper.png
}

input-field {
  check_color = rgb(80eec0) rgb(007acc) 315deg
  fail_color = rgba(241, 76, 76, 1)
  fail_text =
  font_color = rgba(0, 0, 0, 0)
  halign = center
  inner_color = rgba(0, 0, 0, 0)
  outer_color = rgba(0, 0, 0, 0)
  outline_thickness = 1
  placeholder_text =
  position = 0
  rounding = 0
  size = 1918, 1078
  valign = center
}

# TIME
label {
  font_family = RobotoMono
  font_size = 90
  halign = right
  position = -30, 0
  text = $TIME
  valign = top
}

# DATE
label {
  font_family = RobotoMono
  font_size = 22
  halign = right
  position = -30, -150
  text = cmd[update:60000] date +"%A, %d %B %Y"
  valign = top
}
