##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hide gaps/border on fullscreen
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:fullscreen true
windowrule = rounding 0, match:fullscreen true

# Set kitty background opacity
windowrule = opacity 0.8 0.8, match:class kitty
